---
- name: Deploy web application
  hosts: webservers
  become: yes

  tasks:
    - name: Install required packages and dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - python3
        - python3-pip
        - git

    - name: Clone the web application code from Git
      git:
        repo: https://github.com/your-repo-name/your-app.git
        dest: /opt/your-app

    - name: Build the application
      shell: |
        cd /opt/your-app
        pip3 install -r requirements.txt
        python3 setup.py install

    - name: Start the application
      systemd:
        name: your-app
        state: started
        enabled: yes


# ansible-playbook deploy.yml -i inventory.txt
# inventory.txt is a file that contains the list of web servers that the playbook should be executed on. Ansible will connect to each of the web servers and execute the tasks defined in the playbook.